call plug#begin()

set nocompatible
source $VIMRUNTIME/vimrc_example.vim

" basic windows key bindings
source $VIMRUNTIME/mswin.vim
behave mswin


colorscheme open-color

syntax on

set expandtab 
set tabstop=4
set shiftwidth=4

set number
set ignorecase
set noerrorbells visualbell t_vb=

set noundofile
set nobackup

