
set nocompatible
source $VIMRUNTIME/vimrc_example.vim

" basic windows key bindings
source $VIMRUNTIME/mswin.vim
behave mswin

colorscheme josh-console

syntax on

set expandtab 
set tabstop=4
set shiftwidth=4

set number
set ignorecase
set noerrorbells visualbell t_vb=

set noundofile
set nobackup

map <F5> :wall!<CR>:!sbcl --load foo.cl<CR><CR>

